# Generated by Django 3.2 on 2021-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('mal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('genres', models.TextField()),
                ('sypnopsis', models.TextField()),
                ('group', models.CharField(max_length=10)),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
