# Generated by Django 3.2 on 2021-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeAll',
            fields=[
                ('mal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('genres', models.TextField()),
                ('sypnopsis', models.TextField()),
                ('group', models.CharField(max_length=10)),
                ('popularity', models.IntegerField()),
                ('members', models.IntegerField()),
                ('favorites', models.IntegerField()),
            ],
        ),
    ]
